server:
    port: 8086

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8093/eureka

spring:
    application:
        name: user-profile-service
    data:
        mongodb:
            database: signup
            host: localhost
            port: 27017
    rabbitmq:
        host: localhost
        port: 5672
jsh:
    rabbitmq:
        queue: jsh.queuereg
        exchange: jsh.directreg
        routingkey: jsh.routingkeyreg
jsf:
    rabbitmq:
        queue: jsf.queuereg
        exchange: jsf.directreg
        routingkey: jsf.routingkeyreg
jsi:
  rabbitmq:
    queue: jsi.queuereg
    exchange: jsi.directreg
    routingkey: jsi.routingkeyreg