server:
  port: ${PORT:0}

spring:
  application:
    name: questionanswerservice
  data:
    mongodb:
      database: ques_db
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8093/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
jsa:
  rabbitmq:
    queue: jsa.queue1
    exchange: jsa.direct1
    routingkey: jsa.routingkey1
jsd:
  rabbitmq:
    queue: jsd.queue1
    exchange: jsd.direct1
    routingkey: jsd.routingkey1
jse:
  rabbitmq:
    queue: jse.queue1
    exchange: jse.direct1
    routingkey: jse.routingkey1
jsf:
  rabbitmq:
    queue: jsf.queue1
    exchange: jsf.direct1
    routingkey: jsf.routingkey1