server:
  port: 8091


security:
  require-ssl: true

spring:
  application:
    name: my-profile-service
  data:
    mongodb:
      database: myprofile_db
      host: localhost
      port: 27017
jsi:
  rabbitmq:
    queue: jsi.queuereg
    exchange: jsi.directreg
    routingkey: jsi.routingkeyreg

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8093/eureka